ci update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,19 +30,22 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
-        
+
+    - name: Format code with black
+      run: |
+        black . 
+
     - name: Lint with Flake8
       id: flake8
       continue-on-error: true
       run: |
         flake8 .  
 
-    
-    #- name: Check if 'Lint with Flake8' step failed
-     # if: steps.flake8.outcome != 'success'
-      #run: |
-       # echo "flake8 failed"
-        #exit 1
+    - name: Check if 'Lint with Flake8' step failed
+      if: steps.flake8.outcome != 'success'
+      run: |
+        echo "flake8 failed"
+        exit 1
 
 
 
