ci testing

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,11 +37,12 @@ jobs:
       run: |
         flake8 .  
 
-    - name: Check if 'Lint with Flake8' step failed
-      if: steps.flake8.outcome != 'success'
-      run: |
-        echo "flake8 failed"
-        exit 1
+    
+    #- name: Check if 'Lint with Flake8' step failed
+     # if: steps.flake8.outcome != 'success'
+      #run: |
+       # echo "flake8 failed"
+        #exit 1
 
 
 
